// Generates design-system/_shared/icons.jsx from @phosphor-icons/react
// Every Phosphor icon becomes available as Icon<Name> (regular weight).
// Run via: npm run gen-icons  (or automatically via prebuild/predev)

import { readFileSync, readdirSync, writeFileSync } from 'fs'
import { resolve, join, dirname } from 'path'
import { fileURLToPath } from 'url'
const __dirname = dirname(fileURLToPath(import.meta.url))
const fs = { readFileSync, readdirSync, writeFileSync }
const path = { resolve, join }

const DEFS_DIR = path.resolve(__dirname, '../../node_modules/@phosphor-icons/react/dist/defs');
const OUT_FILE = path.resolve(__dirname, '../../design-system/_shared/icons.jsx');

// Semantic aliases — backward compat + friendlier names for the AI
const ALIASES = {
  IconEdit:       'IconNotePencil',
  IconEditFill:   'IconNotePencilFill',
  IconClose:      'IconX',
  IconGear:       'IconGear',       // same name
  IconSearch:     'IconMagnifyingGlass',
  IconShare:      'IconShare',      // same
  IconExternal:   'IconArrowSquareOut',
  IconRevert:     'IconArrowCounterClockwise',
  IconUsers:      'IconUsers',      // same
  IconMore:       'IconDotsThreeVertical',
};

// Extract all { d: "..." } values from the "regular" weight section
function extractPaths(content) {
  const regularIdx = content.indexOf('"regular"');
  if (regularIdx === -1) return null;

  // Find the end of this entry (next weight or end of map)
  const nextEntry = content.indexOf('\n  ],\n  [', regularIdx);
  const section = nextEntry === -1
    ? content.slice(regularIdx)
    : content.slice(regularIdx, nextEntry);

  const paths = [];
  const re = /\{ d: "([^"]+)"/g;
  let m;
  while ((m = re.exec(section)) !== null) paths.push(m[1]);
  return paths.length ? paths : null;
}

function toPascalCase(name) {
  // Already PascalCase from filename (e.g. "NotePencil")
  return name;
}

const files = fs.readdirSync(DEFS_DIR)
  .filter(f => f.endsWith('.es.js') && f !== 'index.es.js');

const icons = {}; // name -> paths[]

for (const file of files) {
  const name = file.replace('.es.js', '');
  if (!name) continue;
  try {
    const content = fs.readFileSync(path.join(DEFS_DIR, file), 'utf8');
    const paths = extractPaths(content);
    if (paths) icons[name] = paths;
  } catch (_) {}
}

const names = Object.keys(icons).sort();
console.log(`Found ${names.length} icons with regular weight paths`);

// Build output
const lines = [];

lines.push(`// Icons — ALL Phosphor Icons (phosphor-icons.com), Regular weight.`);
lines.push(`// AUTO-GENERATED by builder/scripts/gen-icons.js — do not edit by hand.`);
lines.push(`// Run: cd builder && npm run gen-icons`);
lines.push(`//`);
lines.push(`// Usage: <IconNotePencil size={16} />  <IconTrash size={16} />  etc.`);
lines.push(`// Semantic aliases: IconEdit=IconNotePencil, IconClose=IconX, etc.`);
lines.push(``);

// Base SVG component — supports single or multiple paths
lines.push(`const PhIcon = ({ d, paths, size = 16, style, className }) => (`);
lines.push(`  <svg`);
lines.push(`    xmlns="http://www.w3.org/2000/svg"`);
lines.push(`    width={size}`);
lines.push(`    height={size}`);
lines.push(`    viewBox="0 0 256 256"`);
lines.push(`    fill="currentColor"`);
lines.push(`    aria-hidden="true"`);
lines.push(`    style={style}`);
lines.push(`    className={className}`);
lines.push(`  >`);
lines.push(`    {(paths || (d ? [d] : [])).map((p, i) => <path key={i} d={p} />)}`);
lines.push(`  </svg>`);
lines.push(`);`);
lines.push(``);

// One const per icon
for (const name of names) {
  const paths = icons[name];
  if (paths.length === 1) {
    lines.push(`const Icon${name} = (p) => <PhIcon {...p} d="${paths[0]}" />;`);
  } else {
    const pathsJson = JSON.stringify(paths);
    lines.push(`const Icon${name} = (p) => <PhIcon {...p} paths={${pathsJson}} />;`);
  }
}

lines.push(``);

// Semantic aliases
lines.push(`// Semantic aliases for backward compat`);
for (const [alias, target] of Object.entries(ALIASES)) {
  if (alias !== target && icons[target.replace('Icon', '')]) {
    lines.push(`const ${alias} = ${target};`);
  }
}
lines.push(``);

// Register everything on window
const allVarNames = names.map(n => `Icon${n}`);
const aliasVarNames = Object.entries(ALIASES)
  .filter(([alias, target]) => alias !== target && icons[target.replace('Icon', '')])
  .map(([alias]) => alias);

const allExports = [...allVarNames, ...aliasVarNames];
const chunks = [];
for (let i = 0; i < allExports.length; i += 8) {
  chunks.push('  ' + allExports.slice(i, i + 8).join(', '));
}
lines.push(`Object.assign(window, {`);
lines.push(chunks.join(',\n'));
lines.push(`});`);
lines.push(``);

const output = lines.join('\n');
fs.writeFileSync(OUT_FILE, output);

const kb = Math.round(Buffer.byteLength(output, 'utf8') / 1024);
console.log(`✓ icons.jsx — ${names.length} icons | ${kb} KB`);
console.log(`  Aliases: ${Object.keys(ALIASES).join(', ')}`);
