// Reads design-system/_design_system/colors_and_type.css and generates
// builder/system-prompt/design-tokens.md for the builder AI.
// Run via: npm run gen-tokens  (or automatically via prebuild/predev)

import { readFileSync, writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const CSS_FILE = resolve(__dirname, '../../design-system/_design_system/colors_and_type.css')
const OUT_FILE = resolve(__dirname, '../system-prompt/design-tokens.md')

const css = readFileSync(CSS_FILE, 'utf8')

// ── Extract CSS variables ──────────────────────────────────────────────────
function extractVars(css) {
  const vars = []
  // Match --var-name: value; with optional inline comment
  const re = /^\s*(--en-[\w-]+)\s*:\s*([^;]+?)\s*;(?:[ \t]*\/\*([^*\n]+)\*\/)?/gm
  let m
  while ((m = re.exec(css)) !== null) {
    vars.push({ name: m[1], value: m[2].trim(), comment: (m[3] || '').trim() })
  }
  return vars
}

// ── Extract class rules ────────────────────────────────────────────────────
function extractClasses(css) {
  const classes = []
  const re = /^(\.en-[\w-]+)\s*\{([^}]+)\}/gm
  let m
  while ((m = re.exec(css)) !== null) {
    const name = m[1]
    const body = m[2].trim().replace(/\s+/g, ' ')
    // Extract key properties
    const font = (body.match(/font:\s*([^;]+)/) || [])[1]?.trim()
    const letter = (body.match(/letter-spacing:\s*([^;]+)/) || [])[1]?.trim()
    const transform = (body.match(/text-transform:\s*([^;]+)/) || [])[1]?.trim()
    classes.push({ name, font, letter, transform })
  }
  return classes
}

const vars = extractVars(css)
const classes = extractClasses(css)

// ── Group variables ────────────────────────────────────────────────────────
const groups = {
  spacing:    vars.filter(v => v.name.startsWith('--en-space')),
  radius:     vars.filter(v => v.name.startsWith('--en-radius')),
  shadow:     vars.filter(v => v.name.startsWith('--en-shadow')),
  duration:   vars.filter(v => v.name.startsWith('--en-duration') || v.name === '--en-easing'),
  colorBrand: vars.filter(v => v.name.match(/--en-(primary|secondary|error|success|warning)/)),
  colorFg:    vars.filter(v => v.name.match(/--en-(fg|icon|sidebar)/)),
  colorBg:    vars.filter(v => v.name.match(/--en-bg/) && !v.name.includes('primary')),
  colorBorder:vars.filter(v => v.name.match(/--en-(divider|border)/)),
  colorData:  vars.filter(v => v.name.startsWith('--en-data') || v.name.startsWith('--en-product')),
  colorGraph: vars.filter(v => v.name.startsWith('--en-graph')),
  misc:       vars.filter(v => v.name.match(/--en-(black|white|logo|action|outlined|heading|text-|font)/)),
}

// ── Typography groups ──────────────────────────────────────────────────────
const typeGroups = {
  headings:   classes.filter(c => c.name.match(/\.en-h\d/)),
  body:       classes.filter(c => c.name.startsWith('.en-body')),
  subtitle:   classes.filter(c => c.name.startsWith('.en-subtitle')),
  caption:    classes.filter(c => c.name.startsWith('.en-caption')),
  overline:   classes.filter(c => c.name.startsWith('.en-overline')),
  button:     classes.filter(c => c.name.startsWith('.en-btn')),
  tab:        classes.filter(c => c.name.startsWith('.en-tab')),
  table:      classes.filter(c => c.name.startsWith('.en-table')),
  code:       classes.filter(c => c.name.startsWith('.en-code')),
}

function varRow(v) {
  const comment = v.comment ? ` — ${v.comment}` : ''
  return `\`${v.name}\` = \`${v.value}\`${comment}`
}

function classRow(c) {
  let desc = c.font ? `font: \`${c.font}\`` : ''
  if (c.letter) desc += ` · letter-spacing: ${c.letter}`
  if (c.transform) desc += ` · ${c.transform}`
  return `\`${c.name}\` — ${desc}`
}

// ── Build markdown ─────────────────────────────────────────────────────────
const lines = []

lines.push(`<!-- AUTO-GENERATED by builder/scripts/gen-tokens.js — do not edit by hand -->`)
lines.push(`<!-- source: design-system/_design_system/colors_and_type.css -->`)
lines.push(``)
lines.push(`# ennabl Design Tokens`)
lines.push(``)
lines.push(`These tokens are injected into every builder preview. Use them directly — no imports needed.`)
lines.push(``)
lines.push(`**Golden rule: always use tokens instead of raw values.**`)
lines.push(`- Use \`var(--en-space-4)\` not \`16px\``)
lines.push(`- Use \`var(--en-primary)\` not \`#0000C5\``)
lines.push(`- Use \`className="en-body2"\` not \`font: 400 14px/20px ...\``)
lines.push(``)
lines.push(`---`)

// Spacing
lines.push(``)
lines.push(`## Spacing`)
lines.push(``)
lines.push(`Base unit: 4px. Always use the scale — never raw px for layout spacing.`)
lines.push(``)
groups.spacing.forEach(v => lines.push(`- ${varRow(v)}`))

// Radii
lines.push(``)
lines.push(`## Border Radius`)
lines.push(``)
groups.radius.forEach(v => lines.push(`- ${varRow(v)}`))

// Color — Brand
lines.push(``)
lines.push(`## Colors — Brand`)
lines.push(``)
groups.colorBrand.forEach(v => lines.push(`- ${varRow(v)}`))

// Color — Foreground / Text / Icon
lines.push(``)
lines.push(`## Colors — Text & Icon`)
lines.push(``)
groups.colorFg.forEach(v => lines.push(`- ${varRow(v)}`))
groups.misc.filter(v => v.name.startsWith('--en-text-')).forEach(v => lines.push(`- ${varRow(v)}`))

// Color — Background
lines.push(``)
lines.push(`## Colors — Background`)
lines.push(``)
groups.colorBg.forEach(v => lines.push(`- ${varRow(v)}`))

// Color — Border / Divider
lines.push(``)
lines.push(`## Colors — Border & Divider`)
lines.push(``)
groups.colorBorder.forEach(v => lines.push(`- ${varRow(v)}`))
groups.misc.filter(v => v.name.match(/--en-(action|outlined)/)).forEach(v => lines.push(`- ${varRow(v)}`))

// Color — Data / Product
lines.push(``)
lines.push(`## Colors — Data Types`)
lines.push(``)
lines.push(`Use these for data category labels, avatars, and chart series — not for UI chrome.`)
lines.push(``)
groups.colorData.forEach(v => lines.push(`- ${varRow(v)}`))

// Typography classes
lines.push(``)
lines.push(`## Typography Classes`)
lines.push(``)
lines.push(`Apply with \`className\`. Font is Inter (loaded via @font-face).`)
lines.push(``)

lines.push(`**Headings**`)
typeGroups.headings.forEach(c => lines.push(`- ${classRow(c)}`))

lines.push(``)
lines.push(`**Body**`)
typeGroups.body.forEach(c => lines.push(`- ${classRow(c)}`))

lines.push(``)
lines.push(`**Subtitle**`)
typeGroups.subtitle.forEach(c => lines.push(`- ${classRow(c)}`))

lines.push(``)
lines.push(`**Caption**`)
typeGroups.caption.forEach(c => lines.push(`- ${classRow(c)}`))

lines.push(``)
lines.push(`**Overline** (uppercase, spaced)`)
typeGroups.overline.forEach(c => lines.push(`- ${classRow(c)}`))

lines.push(``)
lines.push(`**Button text**`)
typeGroups.button.forEach(c => lines.push(`- ${classRow(c)}`))

lines.push(``)
lines.push(`**Tab labels**`)
typeGroups.tab.forEach(c => lines.push(`- ${classRow(c)}`))

lines.push(``)
lines.push(`**Table**`)
typeGroups.table.forEach(c => lines.push(`- ${classRow(c)}`))

lines.push(``)
lines.push(`**Code**`)
typeGroups.code.forEach(c => lines.push(`- ${classRow(c)}`))

// Shadows & Motion
lines.push(``)
lines.push(`## Elevation & Motion`)
lines.push(``)
groups.shadow.forEach(v => lines.push(`- ${varRow(v)}`))
lines.push(``)
groups.duration.forEach(v => lines.push(`- ${varRow(v)}`))

lines.push(``)

const output = lines.join('\n')
writeFileSync(OUT_FILE, output)

const varCount = vars.length
const classCount = classes.length
console.log(`✓ design-tokens.md — ${varCount} variables, ${classCount} type classes`)
